# -*- coding: utf-8 -*-
"""laboratorio4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOOe6-d6486GCr4GYkS6CQd_vcq2b5Cv
"""

n1 = int(input("Digite nota 1.:"))
n2 = int(input("Digite nota 2.:"))
print("-" *17)
print("1- Soma das notas\n2- Média Simples\n3- Média Ponderada\n4- Maior nota\n5- Menor nota\n6- Diferença absoluta entre as notas\n7- Percentual de aproveitamento\n8- Situação do aluno (se aprovado)")
operacao = int(input(f"\nEscolha operação a ser realizada com os números {n1} e {n2}.:"))

match operacao:
  case 1:
    soma = n1 + n2
    print(f"\nO resultado da soma de {n1} e {n2} é {soma}")
  case 2:
    media = n1 + n2/2
    print(f"\nO resultado da média de {n1} e {n2} é {media}")
  case 3:
    peso1 = int(input("Digite o peso da nota 1.:"))
    peso2 = int(input("Digite o peso da nota 2.:"))
    ponderada = (n1*peso1) + (n2*peso2)/ (peso1 + peso2)
    print(f"\nO resultado da média ponderada de {n1} e {n2} é {ponderada}")
  case 4:
    if n1 > n2:
      print(f"\nO maior número é {n1}")
    else:
      print(f"\nO maior número é {n2}")
  case 5:
    if n1 > n2:
      print(f"\nO menor número é {n2}")
    else:
      print(f"\nO menor número é {n1}")
  case 6:
    if n1 > n2:
      diferenca = n1 - n2
    else:
      diferenca = n2 - n1
    print(f"\nA diferença absoluta é: {diferenca}")
  case 7:
    med = ((n1 + n2)/2)*1
    print(f"\nAproveitamento é de {med}%")
  case 8:
    if ((n1+n2)/2) > 70:
      print("\nAluno aprovado, atingiu média 70")
    else:
      print("\nAluno reprovado, não atingiu a média 70")
  case _:
    print("\nOpção inválida !!")

km = float(input("Digite a distância do destino.:"))
peso = float(input("Digite o peso da encomenda.:"))
base = float(input("Digite o valor do frete por KM.: "))

frete1 = km * base
print(f"Valor do frete base é R${frete1:.2f}")

if km < 50:
  if peso < 5:
    acrescimo = frete1 * 0.10
    novo_frete = acrescimo + frete1
    print(f"Valor com acréscimo R${novo_frete:.2f}")
  else:
    print("Não houve acréscimo")
else:
  if km >= 50 and km <300:
    if peso >= 5 and peso <= 20:
      acrescimo = frete1 * 0.20
      novo_frete = acrescimo + frete1
      print(f"Valor com acréscimo R${novo_frete:.2f}")
    else:
      print("Não houve acréscimo")
  else:
    if km>300 and peso>20:
      acrescimo = frete1 * 0.30
      novo_frete = acrescimo + frete1
      print(f"Valor com acréscimo R${novo_frete:.2f}")

    else:
      print("Não houve acréscimo")

print("SIMULAÇÃO DE FINANCIAMENTO PARA PACOTE DE VIAGENS")
pct = float(input("Digite o valor do pacote da viagem.: "))
sal = float(input("Digite o seu salário mensal.: "))
meses = int(input("Digite o valor de meses para pagamento.: "))

parcela = pct/meses

if parcela > (sal * 0.25):
  print("O Banco Master informa: financiamento RECUSADO")
else:
  print("O Banco Master informa: financiamento APROVADO, pode viajar !!")

valor = float(input("Digite o valor do curso.: "))
print("\nFormas de pagamento \n1-Cartão de Crédito \n2-Boleto \n3-Transferência \n")
pagamento = int(input("Digite a forma de pagamento escolhida.: "))

match pagamento:
  case 1:
    parcela = int(input("\nEscolha o número de parcelas, em até 3x sem juros.:"))
    if parcela >= 4:
      juros = (parcela - 3) * 0.02
      valor += valor * juros
      valor_parcela = valor / parcela
      print(f"Total do curso R$ {valor:.2f} conforme selecionado. Em {parcela} parcelas de R${valor_parcela:.2f}")
    else:
      valor_parcela = valor / parcela
      print(f"Total do curso R$ {valor:.2f} conforme selecionado. Em {parcela} parcelas de R${valor_parcela:.2f} ")
  case 2:
    desconto = valor * (10/100)
    desconto = valor - desconto
    print(f"Total do curso R$ {desconto:.2f} conforme selecionado")
  case 3:
    desconto = valor * (10/100)
    desconto = valor - desconto
    print(f"Total do curso R$ {desconto:.2f} conforme selecionado.")
  case _:
    print("Opção escolhida é inválida, necessário escolher entre [1-3]")